[package]
name = "sq"
version = "0.1.0"
edition = "2024"

[dependencies]
datafusion = { version = "47.0.0", default-features = false }
sqlparser = "0.56.0"
tokio = { version = "1.45.0", features = ["rt-multi-thread"] }
unicode-segmentation = "1.12.0"
